export enum AuditAction {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  STATUS_CHANGE = 'STATUS_CHANGE',
  DOCUMENT_GENERATED = 'DOCUMENT_GENERATED',
  SUBMITTED_FOR_REVIEW = 'SUBMITTED_FOR_REVIEW',
  APPROVED = 'APPROVED',
}
